[package]
name = "coremidi"
version = "0.1.0"
authors = ["Christian Perez-Llamas"]
description = "CoreMIDI library for Rust"
license = "MIT"
homepage = "https://github.com/chris-zen/coremidi"

[dependencies]
core-foundation-sys = "0.2"
core-foundation = "0.2"
coremidi-sys = { git = "https://github.com/chris-zen/coremidi-sys", branch="fix-packed-structs" }
time = "0.1"
